### ISSUE TITLE
Pay Wall Issue

### ISSUE THREAD

**Issue by jimbrayrcp** [CodeSlicing/pure-swift-ui-tools#3]
The instructions for instillation which you have linked in the README are behind a pay wall.

**Comment by Brett-Best** [comment]
Do you mean this link https://betterprogramming.pub/add-swift-package-dependency-to-an-ios-project-with-xcode-11-remote-local-public-private-3a7577fac6b2?

**Comment by Brett-Best** [comment]
Only link I could find that could be behind a wall now, @jimbrayrcp refer to https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app for the official documentation from Apple.

**Comment by jimbrayrcp** [comment]
LOL, Yeah, I figured it out. Thanks
But it may be nice for new folks to see something that explains it.

**Comment by Brett-Best** [comment]
Yeah, agreed. @CodeSlicing could swap out the current link with the Apple link (:

**Comment by CodeSlicing** [comment]
Thanks for the heads up. I'll get this sorted today! 👍🏻
